title: Site
pages: true
fields:
    title:
        label: Title
        type:  text
    initial:
        label: Initial
        type:  text
    social:
        label: Social Links
        type: structure
        entry: >
            {{label}} ({{class}})<br />
            @ {{url}} - {{popup}}
        fields:
            label:
                label: Label
                type: text
            url:
                label: URL
                type: text
            class:
                label: Class
                type: text
            popup:
                label: Popup
                type: radio
                options:
                    external: External
                    internal: Internal
    author:
        label: Author
        type:  text
    description:
        label: Description
        type:  textarea
    keywords:
        label: Keywords
        type:  tags
    copyright:
        label: Copyright
        type:  textarea
